### ISSUE TITLE
Cannot pull Docker image to AWS EC2 instances

### ISSUE THREAD

**Issue by JiaweiZhuang** [singularityhub/sregistry-cli#72] opened 2018-02-07 05:33 UTC
Singularity version:
```
ubuntu@ip-172-31-74-72:~/singularity$ singularity --version
2.4.2-master.g09fb002
```

Error message:
```
ubuntu@ip-172-31-74-72:~/singularity$ singularity pull --name funny.simg docker://godlovedc/lolcow
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/godlovedc/lolcow:latest
Cache folder set to /home/ubuntu/.singularity/docker
[6/6] |===================================| 100.0%
Importing: base Singularity environment
Importing: /home/ubuntu/.singularity/docker/sha256:9fb6c798fa41e509b58bccc5c29654c3ff4648b608f5daa67c1aab6a7d02c118.tar.gz

gzip: /home/ubuntu/.singularity/docker/sha256:9fb6c798fa41e509b58bccc5c29654c3ff4648b608f5daa67c1aab6a7d02c118.tar.gz: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Cleaning up...
ERROR: pulling container failed!
```

Steps to reproduce error:
1. Launch Ubuntu Server 16.04 (ami-66506c1c) on AWS.
2. Install the master branch of singularity as described by the [docs](http://singularity.lbl.gov/docs-installation).
3. Run the above command

Exactly the same problem for Amazon Linux (ami-97785bed). This should be an EC2 problem, not an OS-specific problem. 

Related: singularityware/singularity#1240

**Comment by vsoch** [comment] 2018-02-07 16:59
hey @JiaweiZhuang I'm on an Amazon instance, Ubuntu 16.04 (`ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180126 (ami-79873901)`) and I installed Singularity from master - I can't reproduce this error.

```
singularity --version
2.4.2-master.g09fb002
ubuntu@ip-172-31-21-98:~/singularity$ singularity pull docker://tensorflow/tensorflow
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/tensorflow/tensorflow:latest
Cache folder set to /home/ubuntu/.singularity/docker
[12/12] |===================================| 100.0% 
Importing: base Singularity environment
Importing: /home/ubuntu/.singularity/docker/sha256:1be7f2b886e89a58e59c4e685fcc5905a26ddef3201f290b96f1eff7d778e122.tar.gz
Importing: /home/ubuntu/.singularity/docker/sha256:6fbc4a21b806838b63b774b338c6ad19d696a9e655f50b4e358cc4006c3baa79.tar.gz
Importing: /home/ubuntu/.singularity/docker/sha256:c71a6f8e13782fed125f2247931c3eb20cc0e6428a5d79edb546f1f1405f0e49.tar.gz
Importing: /home/ubuntu/.singularity/docker/sha256:4be3072e5a37392e32f632bb234c0b461ff5675ab7e362afad6359fbd36884af.tar.gz
Importing: /home/ubuntu/.singularity/docker/sha256:06c6d2f5970057aef3aef6da60f0fde280db1c077f0cd88ca33ec1a70a9c7b58.tar.gz
Importing: /home/ubuntu/.singularity/docker/sha256:bbb205835a3ef51712af507afaedfb425748f987140338495c1730437059d366.tar.gz
Importing: /home/ubuntu/.singularity/docker/sha256:8ae21269336ec274ae2ec6cfc8c4114b49deaebef4a25ec1e1726d822a61b1c8.tar.gz
Importing: /home/ubuntu/.singularity/docker/sha256:d39ca440854cfa8a09d53a91f0083b7681a666a9dc260ec60fc16301021cb313.tar.gz
Importing: /home/ubuntu/.singularity/docker/sha256:f2d0596799e58b072e4dfbc0f516cdae8cc73aee639fb7acdec686f2bf20cefb.tar.gz
Importing: /home/ubuntu/.singularity/docker/sha256:14f1d8638444ed34cbf6acfc1ae5035961aed736834fe4adc901330f4fc8b13f.tar.gz
Importing: /home/ubuntu/.singularity/docker/sha256:28cd203f6303bb1fe71346565d2068027a8b9848490eff6d8255917e4c69880f.tar.gz
Importing: /home/ubuntu/.singularity/docker/sha256:7cec7dc064fc943feb6520942f16f303a6d2df9b5ecdeaabe1b5d4cffd6a8085.tar.gz
Importing: /home/ubuntu/.singularity/metadata/sha256:453c01572b38d9a72fa1c8630592621c12017d30ddcec565fc8eb40ac6798b65.tar.gz
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
Building Singularity image...
Singularity container built: ./tensorflow.simg
Cleaning up...
Done. Container is at: ./tensorflow.simg
```

Do you possibly have an old layer (that was a previous errored layer) cached? Try removing the layer cache and doing it again. Or was this specific to Amazon Linux images? And I realize I used a slightly different ami (although same version of ubuntu and server) so I'll try the Amazon Linux next and match your AMI. What I think I'd want to ask you to do is look at the content of the file that failed extraction - it likely is an xml file with an error message.

**Comment by vsoch** [comment] 2018-02-07 17:02
And I did try the godlovedc/lolcow image too, seems to work:

**Comment by vsoch** [comment] 2018-02-07 17:05
Do you have any special settings for your network, etc, or just launched one of the ready-to-go instances? (as I did)

**Comment by vsoch** [comment] 2018-02-07 17:25
woohoo! reproduced! You are using one of the nvidia images I see! Will debug now.

```
$ singularity pull docker://tensorflow/tensorflow
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/tensorflow/tensorflow:latest
Cache folder set to /home/ec2-user/.singularity/docker
[12/12] |===================================| 100.0% 
Importing: base Singularity environment
Importing: /home/ec2-user/.singularity/docker/sha256:1be7f2b886e89a58e59c4e685fcc5905a26ddef3201f290b96f1eff7d778e122.tar.gz

gzip: /home/ec2-user/.singularity/docker/sha256:1be7f2b886e89a58e59c4e685fcc5905a26ddef3201f290b96f1eff7d778e122.tar.gz: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Cleaning up...
ERROR: pulling container failed!
$
```

**Comment by vsoch** [comment] 2018-02-07 17:40
hey @JiaweiZhuang ! I should have tried this with the sregistry client first, no error here (and I didn't do anything!)

```
[ec2-user@ip--xxx-xx-x-xx sregistry-cli]$ sregistry pull docker://tensorflow/tensorflow:latest
[client|docker] [database|sqlite:////home/ec2-user/.singularity/sregistry.db]
Progress |===================================| 100.0% 
Progress |===================================| 100.0% 
Progress |===================================| 100.0% 
Progress |===================================| 100.0% 
Progress |===================================| 100.0% 
Progress |===================================| 100.0% 
Progress |===================================| 100.0% 
Progress |===================================| 100.0% 
Progress |===========|-----------------------|  33.8% 
Progress |===================|---------------|  56.1% 
Progress |===================================| 100.0% 

[12/12] |===================================| 100.0% 
Exploding /usr/local/libexec/singularity/bootstrap-scripts/environment.tar
Exploding /home/ec2-user/.singularity/docker/sha256:1be7f2b886e89a58e59c4e685fcc5905a26ddef3201f290b96f1eff7d778e122.tar.gz
Exploding /home/ec2-user/.singularity/docker/sha256:6fbc4a21b806838b63b774b338c6ad19d696a9e655f50b4e358cc4006c3baa79.tar.gz
Exploding /home/ec2-user/.singularity/docker/sha256:c71a6f8e13782fed125f2247931c3eb20cc0e6428a5d79edb546f1f1405f0e49.tar.gz
Exploding /home/ec2-user/.singularity/docker/sha256:4be3072e5a37392e32f632bb234c0b461ff5675ab7e362afad6359fbd36884af.tar.gz
Exploding /home/ec2-user/.singularity/docker/sha256:06c6d2f5970057aef3aef6da60f0fde280db1c077f0cd88ca33ec1a70a9c7b58.tar.gz
Exploding /home/ec2-user/.singularity/docker/sha256:bbb205835a3ef51712af507afaedfb425748f987140338495c1730437059d366.tar.gz
Exploding /home/ec2-user/.singularity/docker/sha256:8ae21269336ec274ae2ec6cfc8c4114b49deaebef4a25ec1e1726d822a61b1c8.tar.gz
Exploding /home/ec2-user/.singularity/docker/sha256:d39ca440854cfa8a09d53a91f0083b7681a666a9dc260ec60fc16301021cb313.tar.gz
Exploding /home/ec2-user/.singularity/docker/sha256:f2d0596799e58b072e4dfbc0f516cdae8cc73aee639fb7acdec686f2bf20cefb.tar.gz
Exploding /home/ec2-user/.singularity/docker/sha256:14f1d8638444ed34cbf6acfc1ae5035961aed736834fe4adc901330f4fc8b13f.tar.gz
Exploding /home/ec2-user/.singularity/docker/sha256:28cd203f6303bb1fe71346565d2068027a8b9848490eff6d8255917e4c69880f.tar.gz
Exploding /home/ec2-user/.singularity/docker/sha256:7cec7dc064fc943feb6520942f16f303a6d2df9b5ecdeaabe1b5d4cffd6a8085.tar.gz
Exploding /home/ec2-user/.singularity/docker/metadata/sha256:453c01572b38d9a72fa1c8630592621c12017d30ddcec565fc8eb40ac6798b65.tar.gz
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
Building image from sandbox: /tmp/tmpPZu5nP
Building Singularity image...
Singularity container built: /home/ec2-user/.singularity/shub/tensorflow-tensorflow:latest.simg
Cleaning up...

[container][new] tensorflow/tensorflow:latest
Success! /home/ec2-user/.singularity/shub/tensorflow-tensorflow:latest.simg
[ec2-user@ip-xxx-xx-x-xx sregistry-cli]$ 
```
and then it wokrs

```
$ sregistry get tensorflow/tensorflow:latest
/home/ec2-user/.singularity/shub/tensorflow-tensorflow:latest.simg
$ container=$(sregistry get tensorflow/tensorflow:latest)
$ singularity shell $container
Singularity: Invoking an interactive shell within container...

Singularity tensorflow-tensorflow:latest.simg:~/sregistry-cli> 
```
Does this work for you too? You can install sregistry

```
pip install sregistry
```
and for full functionality (recommended, much more stuff to manage images) install sqlalchemy

```
pip install sqlalchemy
```

**Comment by JiaweiZhuang** [comment] 2018-02-07 19:27
@vsoch Thanks! I can pull the image successfully with `sregistry`.

But what's the difference between `sregistry pull` and `singularity pull`? Does this mean that I have to use `sregistry` on EC2?

**Comment by vsoch** [comment] 2018-02-07 19:45
sregistry is s management tool, do optimized for moving images between storage and clouds, naming, etc. singularity won't be able to natively support every remote API, so sregistry Is a little friendly helper for that.

**Comment by vsoch** [comment] 2018-02-08 01:26
thanks again @JiaweiZhuang , closing this issue.

**Closed by vsoch** 2018-02-08 01:26 UTC

**Comment by jerrin92** [comment] 2018-04-18 18:27
Is there a workaround while using a definition file? I am facing the same issue while building a container from `.def`

**Comment by vsoch** [comment] 2018-04-18 18:34
Yes what you can do is build the container with sregistry first, and then use it as a base. For example, if my definition file has this at the top:

```
Bootstrap: docker
From: tensorflow/tensorflow:17.01
```
Instead you could pull with sregistry like:

```
sregistry pull nvidia://tensorflow/tensorflow:17.10
```
And if that creates some image, you find the path with `sregistry get tensorflow/tensorflow:17.10`

Then you would bootstrap the type localimage with the path to the image. Your definition file would be:

```
Bootstrap: localimage
From: /path/to/tensorflow/tensorflow.simg
...
```
And if you haven't tried the singularity-2.x branch that might be worth trying too, I think a fix might be there too!
